# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=brighteyes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - brighteyes_volume:/etc/mysql/conf.d
    ports:
      - 3306:3306

volumes:
  brighteyes_volume:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080